### ISSUE TITLE
Just for info... to support RSP1A

### ISSUE THREAD

**Issue by f4gkr** [f4exb/libmirisdr-4#4] opened 2018-03-20 20:48 UTC
Bonjour,

To add support for the RSP1A : update device.c 
static mirisdr_device_t mirisdr_devices[] = {
    { 0x1df7, 0x2500, "RSP1", "SDRPlay", "RSP1", MIRISDR_HW_SDRPLAY_RSP1 },
    { 0x1df7, 0x3000, "RSP1A", "SDRPlay", "RSP1A", MIRISDR_HW_SDRPLAY_RSP1 }
};

Tested @home

73

**Comment by f4exb** [comment] 2018-03-25 16:10
Did you look at the present device.c? It is there already but unfortunately this is not enough to make it work. It just allows to recognize the device.

**Comment by f4gkr** [comment] 2018-03-25 16:25
The devices are at work, I will check tomorrow


2018-03-25 18:10 GMT+02:00 f4exb <notifications@github.com>:

**Comment by f4exb** [comment] 2020-05-16 08:50
Dupe of #2

**Closed by f4exb** 2020-05-16 08:50 UTC
